/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ITransferListener,
  ITransferListenerInterface,
} from "../ITransferListener";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "from",
        type: "address",
      },
      {
        name: "to",
        type: "address",
      },
      {
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "transfer",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITransferListener__factory {
  static readonly abi = _abi;
  static createInterface(): ITransferListenerInterface {
    return new utils.Interface(_abi) as ITransferListenerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITransferListener {
    return new Contract(address, _abi, signerOrProvider) as ITransferListener;
  }
}
